use k256::Scalar;

/// A single participant's share of the signature.
#[allow(unused)]
#[derive(Debug)]
pub struct SignatureShare {
    share: Scalar,
}

/// ECDSA signature on a message.
///
/// When generated by this library, the signature will be produced by the
/// threshold ECDSA algorithm by Canetti et al.
#[derive(Debug)]
pub struct Signature(k256::ecdsa::Signature);
